### ISSUE TITLE
Error while processing: Cannot read property 'params' of undefined TypeError: Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by GitHubEmploy** [SuperMarcus/pgoogle#1]
mohit@macbook-pro ~ % pgoogle
[?] What do you want to search for? Cake Summary
[?] How many sentences do you need? [number] 7
[?] (Experimental) Automatically replace the words with its synonyms? [yes|no] no
[*] You might be prompt if the search result contains non-standard characters.
[*] Requesting page 1
[*] Skipping synonyms replacing process.
[*] Generating Paragraph...
Error while processing: Cannot read property 'params' of undefined TypeError: Cannot read property 'params' of undefined
    at /usr/local/lib/node_modules/pgoogle/cli.js:135:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Please solve I really want to use this module

**Comment by lexuv2** [comment]
Bump
